name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Almacenar en caché dependencias de Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Ejecutar pruebas unitarias con Maven
        run: mvn test

      - name: Cargar resultados de las pruebas
        uses: actions/upload-artifact@v2
        with:
          name: resultados-de-pruebas
          path: target/surefire-reports